version: '3.8'
services:

  mongo:
    image: mongo:6.0
    container_name: mongo
    networks:
      - graylog

  opensearch:
    image: opensearchproject/opensearch:2.11.1
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
      - "OPENSEARCH_JAVA_OPTS=-Xms1012m -Xmx1012m"
      - cluster.routing.allocation.disk.watermark.low=95%
      - cluster.routing.allocation.disk.watermark.high=98%
      - cluster.routing.allocation.disk.watermark.flood_stage=99%
      - cluster.info.update.interval=1m
    volumes:
      - opensearch_data:/usr/share/opensearch/data
    networks:
      - graylog
    ports:
      - "9200:9200"

  graylog:
    image: graylog/graylog:5.2
    container_name: graylog
    environment:
      - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://localhost:9000/
      - GRAYLOG_ELASTICSEARCH_HOSTS=http://opensearch:9200
      - GRAYLOG_MESSAGE_JOURNAL_MAX_SIZE=600mb
    volumes:
      - graylog_journal:/usr/share/graylog/data/journal
    networks:
      - graylog
    depends_on:
      - mongo
      - opensearch
    ports:
      - "9000:9000"       # Web interface
      - "12201:12201/udp" # GELF UDP input
      - "12201:12201/tcp" # GELF TCP input

networks:
  graylog:

volumes:
  graylog_journal:
  opensearch_data:
